name: CI/CD DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test || echo "Sem testes ainda"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar pasta SSH e configurar chave
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAVE_SSH_EC2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Adicionar host da EC2 aos conhecidos
        run: ssh-keyscan -H ec2-18-222-186-46.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy na EC2
        run: |
          ssh ec2-18-222-186-46.us-east-2.compute.amazonaws.com << 'EOF'
            # Instala Node.js e NPM se necessário
            if ! command -v node &> /dev/null; then
              curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Cria ou entra na pasta do app
            mkdir -p ~/app
            cd ~/app

            # Mata processo Node (se estiver rodando)
            pkill node || true

            # Limpa a pasta do app
            rm -rf *
          EOF

          # Envia arquivos para EC2
          scp -r ./* ec2-18-222-186-46.us-east-2.compute.amazonaws.com:~/app

          # Instala dependências e inicia app
          ssh ec2-18-222-186-46.us-east-2.compute.amazonaws.com << 'EOF'
            cd ~/app
            npm install
            nohup npm start > output.log 2>&1 &
          EOF


