name: CI/CD com Docker e Deploy na EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAVE_SSH_EC2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Adicionar EC2 à lista de hosts conhecidos
        run: |
          ssh-keyscan -H ec2-18-222-186-46.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Enviar arquivos do projeto para EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa" ./ ec2-user@ec2-18-222-186-46.us-east-2.compute.amazonaws.com:~/app

      - name: Rodar deploy com Docker na EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@ec2-18-222-186-46.us-east-2.compute.amazonaws.com << 'EOF'
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh
          EOF
